name: Build and deploy Python project to Azure VM - phoneclassifier

on:
   workflow_run:
    workflows: ["Retrain Model on New Data"]  # must match the name from step 1
    types:
      - completed

env:
  PYTHON_VERSION: '3.9'
  VM_IP: ${{ secrets.VM_IP }}
  VM_USER: ${{ secrets.VM_USER }}
  VM_KEY: ${{ secrets.VM_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t phoneclassifier .

      - name: Save Docker image to tarball
        run: docker save phoneclassifier -o image.tar

      - name: Copy Docker image to VM
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ env.VM_KEY }} image.tar ${{ env.VM_USER }}@${{ env.VM_IP }}:/home/${{ env.VM_USER }}/

      - name: SSH into VM and load/run image
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ env.VM_KEY }} ${{ env.VM_USER }}@${{ env.VM_IP }} << 'EOF'
            docker load -i image.tar
            docker stop phoneclassifier || true
            docker rm phoneclassifier || true
            docker run -d --name phoneclassifier -p 80:80 phoneclassifier
          EOF
