name: Deploy FastAPI App 🚀

on:
  workflow_run:
    workflows: ["Retrain Model on New Data"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: current-time-service
  IMAGE_NAME: fastapi-app

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: $IMAGE_NAME
