name: Deploy to Azure App Service

on:
  workflow_run:
    workflows: ["Retrain Model on New Data"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: current-time-service
  IMAGE_NAME: phone-classifier

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: kv-secret-rotation-sample-appsrv-dev
          resource-group-name: kv-secret-rotation-sample-rg-dev
          package: .