name: Deploy to Azure App Service

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: current-time-service
  IMAGE_NAME: fastapi-app

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain model
        run: python src/train.py

      - name: Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: $IMAGE_NAME
