name: Build and deploy Dockerized FastAPI to Azure Web App - phone-classifier

on:
  workflow_run:
    workflows: ["Retrain Model on New Data"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME_PRODUCTION: ${{ secrets.AZURE_WEBAPP_NAME_PRODUCTION }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  PRODUCTION_APP_URL: ${{secrets.PRODUCTION_APP_URL}}

jobs:
  build_and_deploy:
    name: Deployement Setup
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r webapp/requirements.txt

  build_and_push_to_dockerhub:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build_and_deploy 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  
  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerhub 
    environment:
      name: production
      url: ${{ env.PRODUCTION_APP_URL }}

    steps:
      - name: Deploy to Azure Web App Production with Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_PRODUCTION }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRODUCTION }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'