# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - phoneclassifier

on:
  workflow_run:
    workflows: ["Retrain Model on New Data"]  # Match the 'name' in ci.yml
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
  
      - name: Build Docker image
        run: |
          docker build -t phone-classifier:production .
  
      - name: Run Docker container
        run: |
          docker run -d --name phone-classifier -p 8000:8000 phone-classifier:production
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Push Docker image to Azure Container Registry
        run: |
          az login
          az acr login --name phoneclassifierregistry
          
          docker pull mcr.microsoft.com/mcr/hello-world
          docker tag mcr.microsoft.com/mcr/hello-world phoneclassifier.azurecr.io/samples/hello-world
          
          docker push phoneclassifier.azurecr.io/samples/hello-world

      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: python-app

      # - name: Unzip artifact for deployment
      #   run: unzip release.zip

      
      # - name: Login to Azure
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_28610A281DC1413C93185B90503E1EDA }}
      #     tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFA690A1319F459B90BEDE2700B997E5 }}
      #     subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C012800DDC7841E1B41D35EDBADB4BBC }}

      # - name: 'Deploy to Azure Web App'
      #   uses: azure/webapps-deploy@v3
      #   id: deploy-to-webapp
      #   with:
      #     app-name: 'phoneclassifier'
      #     slot-name: 'Production'