name: Build and deploy Python project to Azure Function App - phoneclassifier

on:
  workflow_run:
    workflows: ["Retrain Model on New Data"]
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name phoneclassifier

      - name: Build Docker image
        run: |
          docker build -t phoneclassifier.azurecr.io/phone-classifier:production .

      - name: Push Docker image to ACR
        run: |
          docker push phoneclassifier.azurecr.io/phone-classifier:production

      - name: Run container (optional check)
        run: |
          docker run --rm phoneclassifier.azurecr.io/phone-classifier:production

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'phoneclassifier'
          slot-name: 'Production'
          images: 'phoneclassifier.azurecr.io/phone-classifier:production'