name: Build and deploy Dockerized FastAPI to Railway

on:
  workflow_run:
    workflows: ["Retrain Model on New Data Changes"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes
      actions: read

    env:
      MLFLOW_PORT: 5000
      MLFLOW_IMAGE: ghcr.io/mlflow/mlflow:v2.12.1
      MLFLOW_VOLUME: ${{ github.workspace }}/mlruns
      BRANCH_NAME: work-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MLflow Tracking Server
        run: |
          docker run -d -p $MLFLOW_PORT:$MLFLOW_PORT \
            -v $MLFLOW_VOLUME:/mlflow/mlruns \
            $MLFLOW_IMAGE mlflow server \
            --backend-store-uri /mlflow/mlruns \
            --default-artifact-root /mlflow/mlruns \
            --host 0.0.0.0 \
            --port $MLFLOW_PORT