name: Retrain Model on New Data

on:
   push:
    paths:
        - "data/**"

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update trained models"
          file_pattern: "models/**"

  build:
    runs-on: ubuntu-latest
    needs: train
    permissions:
      contents: write
    steps:
      - name: Build Docker image
        run: |
          docker build -t phone-classifier .
      
      - name: Push Docker image to registry
        run: |
          docker login phoneclassifier.azurecr.io
          docker tag production phoneclassifier.azurecr.io/production 
          docker push phoneclassifier.azurecr.io/production